### ISSUE TITLE
Double Prompt

### ISSUE THREAD

**Issue by creese** [porterjamesj/virtualenvwrapper.el#16]
This is great little tool that just works. My issue is largely cosmetic. When I create a new shell, I get a double prompt that looks like this.

[user@host ~]$ (environ)[user@host ~]$

Any idea why?

**Comment by porterjamesj** [comment]
@creese doing some cleanup and I'm going to close this. While I agree it's an annoyance, I don't think it's possible to fix it, as I explained above. Let me know if you have any more questions or ideas!
