### ISSUE TITLE
Allow specifying the python interpreter

### ISSUE THREAD

**Issue by Wilfred** [porterjamesj/virtualenvwrapper.el#18]
With a prefix environment to `venv-mkvirtualenv` I'd like to specify which python interpreter to use. This is useful if I want to create a Python 2 virtualenv on a box where Python 3 is the default, or if I want a pypy virtualenv.

**Comment by bradyt** [comment]
I'm not sure I understand. If I do `mkvirtualenv -p python3 an-env` on command line, shouldn't an `M-x venv-workon` call use `python3`? However, it seems `C-u 3 M-x venv-workon` will use python3, so at least it is possible.

**Comment by bradyt** [comment]
Hmm, disregard. Now `M-x venv-workon` and a call to interactive gives the virtualenv's version of python. Sorry for noise.
