### ISSUE TITLE
Specifying venv-location as a remote directory doesn't work.

### ISSUE THREAD

**Issue by exclamaforte** [porterjamesj/virtualenvwrapper.el#19]
It would be really nice if one could set the venv-location to be a remote path using the Tramp remote path syntax. More of a feature request than a bug report.

**Comment by porterjamesj** [comment]
hmmm, interesting, I think you'd have to be constantly keeping the remote venv location in sync with local temporary directory by copying files back and forth; I doubt it would work very well in practice. out of curiosity, what's your use case for this?

**Comment by exclamaforte** [comment]
I tend to do a lot of development in virtual environments on other servers. I would prefer to use eshell because it works so much better with emacs than bash. However, I haven't been able to find a way to get eshell to play nice with remote, virtual environments, so I'm forced to use bash. This is only one of a couple of issues with eshell and Tramp that I've had, so the correct solution might be just to fix Eshell/Tramp integration.

**Comment by porterjamesj** [comment]
I'm on a bit of an issue gardening streak and going to close this. It's been two years, and it's complicated enough that I'm realistically not going to implement it.
