### ISSUE TITLE
venv-workon's prompt should say the current virtualenv

### ISSUE THREAD

**Issue by Wilfred** [porterjamesj/virtualenvwrapper.el#21]
It would be really helpful if calling `M-x venv-workon` gave a prompt along the lines of: `Virtualenv to switch to (currently test-env-foo): `.

Happy to send a PR for this, I just wanted to open an issue to track it.

**Comment by porterjamesj** [comment]
hey! yeah I agree this would be good and a PR would be great.

Also sorry I've let your other issue linger, work has been crazy :/ I agree with what you wrote here https://github.com/porterjamesj/virtualenvwrapper.el/pull/20#issuecomment-71509733, so if you have time to make that change while you're at it I would be happy to merge that also. If not I'm going on vacation in a couple weeks so maybe I can get to it then :)

**Comment by Wilfred** [comment]
No problem. It's completely reasonable to ask capable users to send PRs :). I should be able to send a patch in the next day or so.
