### ISSUE TITLE
Question about using PYTHONPATH

### ISSUE THREAD

**Issue by rlvoyer** [porterjamesj/virtualenvwrapper.el#23]
Hi there,

Thanks for virtualenvwrapper -- it's been super useful to me. But I have one small issue, and I'm not quite sure how to resolve it. I have a couple of virtualenvs for which I set the PYTHONPATH environment variable, and its value is dependent on which virtualenv I'm using. Using virtualenv outside of Emacs, I can manage this by setting the PYTHONPATH on activate, and then resetting it within a postdeactivate hook. Any tips on how to do this with virtualenvwrapper.el? I see that you support various activate/deactivate hooks, but the hooks I'd like to create are environment-specific. I'm a bit of an elisp newb, so thanks for your help.

Robert

**Comment by porterjamesj** [comment]
Thanks!

I think I see what you mean, but just to confirm—you want to run different hooks for different virtualenvs, right? For now probably the best way to do this is just to branch on the value of `venv-current-name` in your hook, e.g. (totally untested code):

```
(add-hook 'venv-postactivate-hook
          (lambda () (if (s-equals? venv-current-name "myenv") 
                           (function-that-sets-up-stuff-for-my-env))))
```

Something like this should work, but I feel like there's a possibility for a better abstraction here and I'll try to think about what it should look like.

**Comment by rlvoyer** [comment]
This looks like exactly what I want, but this doesn't appear to work as you've written it, and since I'm still learning elisp, it's taking me a bit of trial and error to get it right. I'll post a working version when I have it.

**Comment by porterjamesj** [comment]
yeah i literally just typed that into the github comment box. if you get stuck let me know, happy to help debug :) elisp can be a bear for sure

**Comment by rlvoyer** [comment]
Got it! Thanks for your help. Here's what I did:

```lisp
 (defun debug-env ()
  "Set environment variables for debug build"
  (setenv "PYTHONPATH" "...")
  (setenv "FOO" "..."))

(defun release-env ()
  "Set environment variables for release build"
  (setenv "PYTHONPATH" "...")
  (setenv "FOO" "..."))

(add-hook 'venv-postactivate-hook
          (lambda () (if (string= venv-current-name "debug")
                         (debug-env)
                       (if (string= venv-current-name "release")
                           (release-env)))))
```

**Comment by porterjamesj** [comment]
nice! I'll go ahead a close this and try to think of a cleaner way to do this at some point in the future
