### ISSUE TITLE
Release in melpa stable

### ISSUE THREAD

**Issue by favadi** [porterjamesj/virtualenvwrapper.el#34]
Can you tag a release so it is available in melpa stable?

**Comment by porterjamesj** [comment]
Hey! Sorry for long reply. I will admit I don't know how to do this, I wrote this package before MELPA stable existed. Is there a good guide somewhere?

**Comment by favadi** [comment]
It's very simple, just tag a release and melpa stable will do the work :)

**Comment by porterjamesj** [comment]
woah really? fascinating, i will do this soon!

**Comment by favadi** [comment]
@porterjamesj is it stable enough to tag a release? :P

**Comment by porterjamesj** [comment]
Hey! Yes, I have now tagged a release. Sorry for the delay, maintaining open source projects always somehow ends up at the bottom of the TODO list -___-
