### ISSUE TITLE
change to project directory

### ISSUE THREAD

**Issue by mclearc** [porterjamesj/virtualenvwrapper.el#35]
when using virtualenverapper's `workon` command outside of emacs (e.g. in iTerm on OS X) the virtualenv is activated and the pwd is changed to the relevant project directory set when the env was created (as detailed [here](http://virtualenvwrapper.readthedocs.io/en/latest/projects.html)). This doesn't happen with virtualenvwrapper.el. Is such functionality planned? Is it already present and I'm just missing something easy? Thanks.

**Comment by porterjamesj** [comment]
Hi! Thanks for the report. You are correct that this functionality doesn't exist here, the reason being that I was unaware of it since I've never used it 😬 . For the same reason, I will likely not implement it myself, although I would happily accept this as a contribution if you or anyone else wanted to work on it.

**Comment by mclearc** [comment]
Thanks for the project! My elisp skills are pretty limited, but if I get something working I'll definitely submit a pull request.

**Comment by porterjamesj** [comment]
Sounds good—as perhaps an encouragement, I barely know elisp myself when I started working on this :)

**Comment by mclearc** [comment]
Perhaps the easiest thing to do is use the add-hook of post-activation:

```` emacs-lisp
    (add-hook 'venv-postactivate-hook (lambda () (workon-venv)))

    (defun workon-venv ()
     "change directory to project in eshell"
     (eshell/cd (concat venv-project-home venv-current-name)))
````
This also assumes that you've defined `venv-project-home`. Here's one example:

```` emacs-lisp
(defcustom venv-project-home
  (expand-file-name (or (getenv "PROJECT_HOME") "~/projects/"))
    "The location(s) of your virtualenv projects."
    :group 'virtualenvwrapper)
````
