### ISSUE TITLE
Use same name as for final dirs

### ISSUE THREAD

**Issue by shwsun** [porterjamesj/virtualenvwrapper.el#42]
Hello, I noticed that it has to be different names for final dirs. Is there a way to improve it or work around? I always use `.venv` for all my virtualenvs. It would be nice that using different names is no longer a hard requirement.

**Comment by porterjamesj** [comment]
@shwsun heh, I know this day would come eventually when I added this feature. Congrats on being the first person to ask about it in ~3 years :P

Anyway, the code around this is a bit of a mess, and fixing it would require a pretty substantial overhaul of the internals of the package, which I will get to eventually but would like to put off for a while longer. Right now, the only workaround is to use the [projectile integration](https://github.com/porterjamesj/virtualenvwrapper.el#automatically-activating-a-virtualenv-when-using-projectile), which is a bit of a hack but is perfectly happy with all your vitualenvs being called `.venv`. Would that work for you for now?

**Comment by shwsun** [comment]
Sounds great! I will spend some time on that.

**Comment by porterjamesj** [comment]
I'm going to close this, since it's possible to do this with the projectile integration. Someday I will have a Saturday and nothing to do and feel like programming and I will get around to doing the big refactor I describe above to support this in a less hacky way.
