### ISSUE TITLE
anaconda-mode 

### ISSUE THREAD

**Issue by samrayleung** [porterjamesj/virtualenvwrapper.el#44]
I don't know why, each time I active virtualenvwrapper, my installed python packages stop working. Error:
```
anaconda_mode port 64549

Process anaconda-mode killed: 9
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/Users/samray/.emacs.d/anaconda-mode/0.1.7/anaconda_mode-0.1.7-py2.7.egg/anaconda_mode.py", line 17, in <module>
    from jedi import Script, NotFoundError
ModuleNotFoundError: No module named 'jedi'
```
Environment:
OS: Linux
Emacs: 25.1.1
Python: both 2.7 and 3.6 have installed

Configuration about virtualenvwrapper:
```
;;; virtualenvwrapper for virtualenv
(use-package virtualenvwrapper
  :ensure t
  :init (add-hook 'python-mode-hook (lambda()
				      (venv-initialize-interactive-shells)
				      (venv-initialize-eshell))
		  ))
```

Reproduce:
the location of my virtual environment is `/home/samray/Document/Python/detacat/venv`, step as below:
1.  type `M-x RET venv-set-location RET` and then choose my project environment
2.  active by `M-x pyvenv-active`, and 
3. all my python packages don't work? 

could you help me out?

**Comment by samrayleung** [comment]
It turns out that it is something wrong with jedi, I have fix this issue by following comments in anaconda-mode issue discussion. [anaconda-mode/issues/225](https://github.com/proofit404/anaconda-mode/issues/225)

**Comment by porterjamesj** [comment]
Great!
