### ISSUE TITLE
Path Error when using shell

### ISSUE THREAD

**Issue by furkanusta** [porterjamesj/virtualenvwrapper.el#51]
Hi, When I use venv-projectile-workon and then open up shell, it says
...venvbin/activate: No such file or directory

I've fixed this issue by wrapping venv-current-dir with (file-name-as-directory ) at lines 220, 481 and 499

I'd like to send a pull-request but I don't know much elisp and, thus, I am not sure whether it is a correct fix also I am not sure whether all three of them are necessary.

**Comment by porterjamesj** [comment]
@furkanusta thanks for the report! I believe I https://github.com/porterjamesj/virtualenvwrapper.el/pull/53 fixes this, let me know if latest master doesn't work for you.
