### ISSUE TITLE
Does this package work well when using Python2 and Python3  simultaneously?

### ISSUE THREAD

**Issue by nasoundead** [porterjamesj/virtualenvwrapper.el#52]
like "venv-mkvirtualenv", i did not tell it which python version's virtualenv to use.

**Comment by porterjamesj** [comment]
Yep! If you use a [prefix argument](https://www.emacswiki.org/emacs/PrefixArgument) with `venv-mkvirtualenv`, it will prompt for the path to a Python interpreter to use for the new environment, just like virtualenv's `-p` argument.

**Comment by nasoundead** [comment]
Ok. Thanks. I'll try it.

**Comment by nasoundead** [comment]
1、[in sheel]i create a venv with python2
d:\pyenvs>virtualenv.exe -p c:/Python27/python.exe env2
virtualenv.exe -p c:/Python27/python.exe env2
New python executable in d:\pyenvs\env2\Scripts\python.exe
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter c:/Python27/python.exe

d:\pyenvs>ls
ls
env2
env3

d:\pyenvs>

2. [in eshell] there are no env2:
 $ lsvirtualenv 
env3
 $

**Comment by nasoundead** [comment]
And in eshell, mkvirtualenv could not use -p argument, it think "-p" is a vitrualenv name you want to create.
