### ISSUE TITLE
Thank you for EShell support

### ISSUE THREAD

**Issue by azzamsa** [porterjamesj/virtualenvwrapper.el#62]
I spent two days to configure my ansi-term. My .bash_prompt not loaded correctly. So I need to ask help in r/emacs.

I don't aware of this package. activating venv ( `source .../bin/activate`) in Eshell doesn't work.

This package helps me a lot. I have nice Eshell configuration with nice color and eshell pop-up. Yesterday, I  use my broken color ansi-term for presentation. Cause I thought I will never be able to use Eshell for this.

Thank you so much for this package. Now I can use my venv from Eshell. It's very nice :)

I use `venv-set-location` then `venv-workon`. I don't put my venv location in init.el cause I have many venv.

Thanks lot for this awesome package.

**Comment by porterjamesj** [comment]
Aww, thanks for the kind words! Glad it's useful to you :)
