### ISSUE TITLE
Removing  initialize-eshell doesn't affect anything

### ISSUE THREAD

**Issue by azzamsa** [porterjamesj/virtualenvwrapper.el#63]
I like the EShell support. So I explore this package.

My workflow are:

- open Eshell
- `venv-set-location`
- `venv-workon`

But I wondering why removing `(venv-initialize-eshell)` in my init doesn't affect anything. I can still use venv with Eshell.

> support for eshell is turned on by calling venv-initialize-eshell. After doing this, any new eshells you launch will be in the correct virtualenv and have access to installed executables, etc. 

Is `(venv-initialize-eshell)` only for setting correct virtualenv (checking availiablity of `~/.virtualenv`) ?

Thanks

**Comment by porterjamesj** [comment]
`(venv-initialize-eshell)` just creates shortcuts: https://github.com/porterjamesj/virtualenvwrapper.el/blob/master/virtualenvwrapper.el#L539. So you should be able to e.g. just type `workon foo` rather than `(venv-workon foo)` while in eshell, which is a bit more convenient.

**Comment by azzamsa** [comment]
> just type workon foo rather than (venv-workon foo) while in eshell

Oh I get it. Thanks lot.
